name: Generate Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x' # Wersja .NET, dostosuj do swojego projektu

    - name: Install DocFX
      run: |
        sudo apt-get install -y unzip
        wget https://github.com/dotnet/docfx/releases/download/v2.76.0/docfx-linux-x64-v2.76.0.zip
        unzip docfx-linux-x64-v2.76.0.zip -d docfx
        ls -R docfx
     
    - name: Build documentation
      run: |
        mkdir _site
        chmod +x docfx/docfx # Ustaw uprawnienia do wykonania
        ./docfx/docfx build

    - name: Upload documentation as artifact
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: _site
